name: Run Matrix Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [7.2, 7.3, 7.4, 8.0, 8.1, 8.2]
        laravel: [5.8.*, 6.*, 7.*, 8.*, 9.*, 10.*]
        dependency-version: [prefer-stable]
        include:
          -   laravel: 10.*
              testbench: 8.*
          -   laravel: 9.*
              testbench: 7.*
          -   laravel: 8.*
              testbench: 6.*
          -   laravel: 7.*
              testbench: 5.*
          -   laravel: 6.*
              testbench: 4.*
          -   laravel: 5.8.*
              testbench: 3.*
        exclude:
          - laravel: 10.*
            php: 8.0
          - laravel: 10.*
            php: 7.4
          - laravel: 10.*
            php: 7.3
          - laravel: 10.*
            php: 7.2
          - laravel: 9.*
            php: 7.2
          - laravel: 9.*
            php: 7.3
          - laravel: 9.*
            php: 7.4
          - laravel: 8.*
            php: 7.2
          - laravel: 8.*
            php: 8.2
          - laravel: 7.*
            php: 8.1
          - laravel: 7.*
            php: 8.1
          - laravel: 7.*
            php: 8.2
          - laravel: 6.*
            php: 8.1
          - laravel: 6.*
            php: 8.2
          - laravel: 5.8.*
            php: 8.0
          - laravel: 5.8.*
            php: 8.1
          - laravel: 5.8.*
            php: 8.2

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      -   name: Checkout code
          uses: actions/checkout@v3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
            coverage: none

      -   name: Install dependencies
          run: |
            composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
            composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      -   name: Execute tests
          run: vendor/bin/phpunit
